name: Compile IRBEM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install gfortran
      run: |
         sudo apt-get install gfortran

    - name: Show gfortran version
      run: gfortran --version

    - name: Build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: |
        make OS=linux64 ENV=gfortran64 all
        make OS=linux64 ENV=gfortran64 install

  test_python:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Run Python tests
      run: |
        cd python
        python3 -m pip install -r requirements.txt
        python3 -m pip install pytest
        pytest
