name: Compile IRBEM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Install gfortran
      run: |
         sudo apt-get install gfortran

    - name: Show gfortran version
      run: gfortran --version

    - name: Build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: |
        make OS=linux64 ENV=gfortran64 all
        make OS=linux64 ENV=gfortran64 install

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python wrapper
      run: |
        cd python
        python3 -m pip install -r requirements.txt
        python3 -m pip install pytest

    - name: Run Python tests
      run: |
        pytest

  build:
    runs-on: macos-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Show gfortran version
      run: gfortran-11 --version

    - name: Build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: |
        make OS=osx64 ENV=github all
        make OS=osx64 ENV=github install

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python wrapper
      run: |
        cd python
        python3 -m pip install -r requirements.txt
        python3 -m pip install pytest

    - name: Run Python tests
      run: |
        pytest
